"""Munin — the main ReAct agent.

Loops:
  1. Read soul (identity + principles + goals + skills) into system prompt.
  2. Append memory summary + generated-tools catalog (dynamic — refreshed each iteration).
  3. Ask the LLM using OpenAI tool-calling with the exposed tool catalog.
  4. Execute the tool the LLM picked. Log episodic. Feed result back.
  5. Continue until the LLM stops calling tools or the max_iterations budget is spent.

The tool catalog contains a hand-picked selection of native MCP tools (LDAP, Hugin,
Tavily, wake/sleep, memory, forge) PLUS every `gen__*` autogenerated tool. The
autogenerated ones are re-enumerated on every turn — so a tool Munin forges mid-loop
becomes available in the very next step.
"""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Any, Callable

from ..mcp.config import Settings, get_settings
from ..mcp.shared_state import SharedStateStore
from ..mcp import registry
from ..mcp.tools import (
    forge_tool,
    graph_forge_tool,
    hugin_tool,
    ldap_tools,
    munin_tools,
    tavily_tool,
)
from ..subagents.base import (
    _signature_to_openai,  # noqa: PLC2701
    _tool_specs,
    build_tool_catalog,
)
from .llm_client import LLMClient
from .memory import Memory
from .orchestrator import Orchestrator
from .soul import SoulManager

logger = logging.getLogger("munin.agent")

# Tools added to the main agent catalog via state-bound wrappers (no global STATE needed)
_DYNAMIC_TOOL_NAMES: set[str] = {
    "post_agent_message",
    "fetch_agent_messages",
    "ack_agent_message",
    "list_agent_presence",
    "publish_shared_intel",
    "query_shared_intel",
    "claim_shared_task",
    "complete_shared_task",
    "heartbeat_shared_task",
    "list_shared_tasks",
}


# ---------------------------------------------------------------------------
# Native tool catalog — the fixed set Munin can always call.
# ---------------------------------------------------------------------------

_NATIVE_TOOLS: dict[str, Callable[..., dict[str, Any]]] = {
    # LDAP
    "ldap_who_am_i": ldap_tools.ldap_who_am_i,
    "get_current_user_info": ldap_tools.get_current_user_info,
    "get_user_groups": ldap_tools.get_user_groups,
    "ldap_search": ldap_tools.ldap_search,
    "find_kerberoastable_users": ldap_tools.find_kerberoastable_users,
    "find_asrep_roastable_users": ldap_tools.find_asrep_roastable_users,
    "find_domain_admins": ldap_tools.find_domain_admins,
    "dump_domain_structure": ldap_tools.dump_domain_structure,
    # External intel
    "tavily_search": tavily_tool.tavily_search,
    "hugin_search": hugin_tool.hugin_search,
    "hugin_refresh": hugin_tool.hugin_refresh,
    # Munin self-inspection & diagnostics
    "munin_self_diagnose": munin_tools.munin_self_diagnose,
    "munin_read_source": munin_tools.munin_read_source,
    # Munin tools
    "list_generated_tools": munin_tools.list_generated_tools,
    "describe_generated_tool": munin_tools.describe_generated_tool,
    "run_generated_tool": munin_tools.run_generated_tool,
    "soul_read": munin_tools.soul_read,
    "soul_list": munin_tools.soul_list,
    "soul_propose_edit": munin_tools.soul_propose_edit,
    "memory_remember": munin_tools.memory_remember,
    "memory_recall": munin_tools.memory_recall,
    "memory_list": munin_tools.memory_list,
    "episodic_query": munin_tools.episodic_query,
    "munin_wake": munin_tools.munin_wake,
    "munin_wake_list": munin_tools.munin_wake_list,
    # Forging + graph design
    "tool_forge": forge_tool.tool_forge,
    "graph_forge": graph_forge_tool.graph_forge,
    "list_generated_graphs": graph_forge_tool.list_generated_graphs,
    "describe_generated_graph": graph_forge_tool.describe_generated_graph,
    "drop_generated_graph": graph_forge_tool.drop_generated_graph,
    "list_subagent_tools": munin_tools.list_subagent_tools,
}




class MuninAgent:
    def __init__(self, settings: Settings | None = None) -> None:
        self.settings = settings or get_settings()
        self.state = SharedStateStore(self.settings)
        self.memory = Memory(self.state)
        self.soul = SoulManager(self.settings.munin_soul_path, self.settings.munin_data_path)
        self.orchestrator = Orchestrator(self.state)
        self.llm = LLMClient(self.settings)

    # ------------------------------------------------------------------
    # Catalog composition
    # ------------------------------------------------------------------
    def _current_catalog(self) -> dict[str, Callable[..., Any]]:
        catalog: dict[str, Callable[..., Any]] = dict(_NATIVE_TOOLS)
        # Generated tools (forged at runtime — refreshed every turn)
        for row in self.memory.known_tools():
            try:
                fn = registry._load_callable(
                    Path(row["script_path"]),
                    row["signature"].get("function_name") or row["name"].replace("gen__", ""),
                )
                catalog[row["name"]] = fn
            except Exception as exc:
                logger.warning("skip generated tool %s: %s", row["name"], exc)
        # Dynamic tools: messaging, intel, tasks — bound to self.state (no global STATE)
        catalog.update(build_tool_catalog(self.state, _DYNAMIC_TOOL_NAMES))
        return catalog

    def _system_prompt(self) -> str:
        return "\n\n".join(
            [
                self.soul.as_system_prompt(),
                self.memory.summarize_for_prompt(),
                "## Working rules",
                "- Before invoking `tool_forge`, ALWAYS call `list_generated_tools` first — reuse over regeneration.",
                "- To spawn a specialist subagent, use `munin_wake` with a task JSON.",
                "- Escape LDAP filter parameters — call `ldap_search` with filter_template + params, never build raw filters.",
                "- Publish notable findings via `publish_shared_intel` so subagents share knowledge.",
                "- If uncertain, ask a clarifying question by responding without a tool call.",
            ]
        )

    # ------------------------------------------------------------------
    # Loop
    # ------------------------------------------------------------------
    def respond(self, user_input: str, *, max_iterations: int = 8) -> dict[str, Any]:
        import time

        messages: list[dict[str, Any]] = [
            {"role": "system", "content": self._system_prompt()},
            {"role": "user", "content": user_input.strip()},
        ]
        self.memory.log_step(agent="munin", action="user_input", input_data={"text": user_input}, tags=["dialog"])
        final_content = ""
        tool_calls_log: list[dict[str, Any]] = []

        for step in range(max_iterations):
            catalog = self._current_catalog()
            specs = _tool_specs(catalog)
            completion = self.llm.chat(messages=messages, tools=specs, temperature=0.2)
            message = completion["choices"][0]["message"]
            messages.append(message)
            self.memory.log_step(
                agent="munin",
                action="react_step",
                input_data={"step": step},
                output_data={"tool_calls": len(message.get("tool_calls") or []), "content_snippet": (message.get("content") or "")[:400]},
                tags=["react"],
            )
            tool_calls = message.get("tool_calls") or []
            if not tool_calls:
                final_content = message.get("content", "") or ""
                break
            for call in tool_calls:
                tool_name = call["function"]["name"]
                try:
                    args = json.loads(call["function"].get("arguments") or "{}")
                except json.JSONDecodeError:
                    args = {}
                fn = catalog.get(tool_name)
                t0 = time.monotonic()
                if not fn:
                    tool_result = {"ok": False, "error": {"code": "unknown_tool", "message": tool_name}}
                else:
                    try:
                        tool_result = fn(**args)
                    except TypeError as exc:
                        tool_result = {"ok": False, "error": {"code": "bad_args", "message": str(exc)}}
                    except Exception as exc:  # noqa: BLE001
                        tool_result = {"ok": False, "error": {"code": "tool_crashed", "message": str(exc)}}
                elapsed_ms = int((time.monotonic() - t0) * 1000)
                self.memory.log_step(
                    agent="munin",
                    action=f"tool:{tool_name}",
                    input_data=args,
                    output_data={"ok": tool_result.get("ok"), "summary": tool_result.get("summary")},
                    tags=["tool"],
                )
                # Record for the caller (frontend tool-call cards)
                entry: dict[str, Any] = {
                    "name": tool_name,
                    "arguments": args,
                    "elapsed_ms": elapsed_ms,
                    "ok": tool_result.get("ok", True),
                    "summary": tool_result.get("summary", ""),
                }
                if tool_result.get("ok", True):
                    entry["result"] = tool_result.get("data", tool_result)
                else:
                    entry["error"] = tool_result.get("error", {"code": "error", "message": str(tool_result)})
                tool_calls_log.append(entry)
                messages.append(
                    {
                        "role": "tool",
                        "tool_call_id": call["id"],
                        "name": tool_name,
                        "content": json.dumps(tool_result, ensure_ascii=True, default=str)[:8000],
                    }
                )
        else:
            final_content = "(max iterations reached)"

        self.memory.log_step(agent="munin", action="final_response", output_data={"content": final_content[:2000]}, tags=["dialog"])
        return {"content": final_content, "iterations": step + 1, "tool_calls": tool_calls_log}
