"""Munin — the main ReAct agent.

Loops:
  1. Read soul (identity + principles + goals + skills) into system prompt.
  2. Append memory summary + generated-tools catalog (dynamic — refreshed each iteration).
  3. Ask the LLM using OpenAI tool-calling with the exposed tool catalog.
  4. Execute the tool the LLM picked. Log episodic. Feed result back.
  5. Continue until the LLM stops calling tools or the max_iterations budget is spent.

The tool catalog contains a hand-picked selection of native MCP tools (LDAP, Hugin,
Tavily, wake/sleep, memory, forge) PLUS every `gen__*` autogenerated tool. The
autogenerated ones are re-enumerated on every turn — so a tool Munin forges mid-loop
becomes available in the very next step.
"""

from __future__ import annotations

import json
import logging
from collections.abc import Callable
from typing import Any

from ..mcp import registry
from ..mcp.config import Settings, get_settings
from ..mcp.shared_state import SharedStateStore
from ..mcp.main import execute_command
from ..mcp.tools import (
    diagnostics_tool,
    forge_tool,
    graph_forge_tool,
    hugin_tool,
    ldap_tools,
    munin_tools,
    tavily_tool,
)
from ..subagents.base import _tool_specs, build_tool_catalog
from .llm_client import LLMClient
from .memory import Memory
from .orchestrator import Orchestrator
from .soul import SoulManager

logger = logging.getLogger("munin.agent")

# Tools added to the main agent catalog via state-bound wrappers (no global STATE needed).
# Added `shared_state_overview` — previously registered on MCP but invisible to the agent
# (bug documented in .ai/diagnostic_prompt.md).
_DYNAMIC_TOOL_NAMES: set[str] = {
    "post_agent_message",
    "fetch_agent_messages",
    "ack_agent_message",
    "list_agent_presence",
    "upsert_agent_presence",
    "publish_shared_intel",
    "query_shared_intel",
    "claim_shared_task",
    "complete_shared_task",
    "heartbeat_shared_task",
    "list_shared_tasks",
    "shared_state_overview",
}


# ---------------------------------------------------------------------------
# Native tool catalog — the fixed set Munin can always call.
# ---------------------------------------------------------------------------

_NATIVE_TOOLS: dict[str, Callable[..., dict[str, Any]]] = {
    "execute_command": execute_command,
    # LDAP
    "ldap_who_am_i": ldap_tools.ldap_who_am_i,
    "get_current_user_info": ldap_tools.get_current_user_info,
    "get_user_groups": ldap_tools.get_user_groups,
    "ldap_search": ldap_tools.ldap_search,
    "find_kerberoastable_users": ldap_tools.find_kerberoastable_users,
    "find_asrep_roastable_users": ldap_tools.find_asrep_roastable_users,
    "find_domain_admins": ldap_tools.find_domain_admins,
    "dump_domain_structure": ldap_tools.dump_domain_structure,
    # External intel
    "tavily_search": tavily_tool.tavily_search,
    "hugin_search": hugin_tool.hugin_search,
    "hugin_refresh": hugin_tool.hugin_refresh,
    "hugin_neighbors": hugin_tool.hugin_neighbors,
    # Munin self-inspection & diagnostics
    "munin_self_diagnose": munin_tools.munin_self_diagnose,
    "munin_diagnostics":   diagnostics_tool.munin_diagnostics,
    "munin_read_source":   munin_tools.munin_read_source,
    "read_wake_artifact":   munin_tools.read_wake_artifact,
    # Munin tools
    "list_generated_tools": munin_tools.list_generated_tools,
    "describe_generated_tool": munin_tools.describe_generated_tool,
    "run_generated_tool": munin_tools.run_generated_tool,
    "deactivate_generated_tool": munin_tools.deactivate_generated_tool,
    "soul_read": munin_tools.soul_read,
    "soul_list": munin_tools.soul_list,
    "soul_propose_edit": munin_tools.soul_propose_edit,
    "memory_remember": munin_tools.memory_remember,
    "memory_recall": munin_tools.memory_recall,
    "memory_list": munin_tools.memory_list,
    "episodic_query": munin_tools.episodic_query,
    "munin_wake": munin_tools.munin_wake,
    "munin_wake_list": munin_tools.munin_wake_list,
    "subagent_trace": munin_tools.subagent_trace,
    # Forging + graph design
    "tool_forge": forge_tool.tool_forge,
    "graph_forge": graph_forge_tool.graph_forge,
    "list_generated_graphs": graph_forge_tool.list_generated_graphs,
    "describe_generated_graph": graph_forge_tool.describe_generated_graph,
    "drop_generated_graph": graph_forge_tool.drop_generated_graph,
    "list_subagent_tools": munin_tools.list_subagent_tools,
}




class MuninAgent:
    def __init__(self, settings: Settings | None = None) -> None:
        self.settings = settings or get_settings()
        self.state = SharedStateStore(self.settings)
        self.memory = Memory(self.state)
        self.soul = SoulManager(self.settings.munin_soul_path, self.settings.munin_data_path)
        self.orchestrator = Orchestrator(self.state)
        self.llm = LLMClient(self.settings)

    # ------------------------------------------------------------------
    # Catalog composition
    # ------------------------------------------------------------------
    def _current_catalog(self) -> dict[str, Callable[..., Any]]:
        catalog: dict[str, Callable[..., Any]] = dict(_NATIVE_TOOLS)
        # Generated tools (forged at runtime — refreshed every turn)
        for row in self.memory.known_tools():
            try:
                fn = registry._load_callable(
                    registry.resolve_script_path(self.settings, row["script_path"]),
                    row["signature"].get("function_name") or row["name"].replace("gen__", ""),
                )
                catalog[row["name"]] = fn
            except Exception as exc:
                logger.warning("skip generated tool %s: %s", row["name"], exc)
        # Dynamic tools: messaging, intel, tasks — bound to self.state (no global STATE)
        catalog.update(build_tool_catalog(self.state, _DYNAMIC_TOOL_NAMES))
        return catalog

    def _system_prompt(self) -> str:
        return "\n\n".join(
            [
                self.soul.as_system_prompt(),
                self.memory.summarize_for_prompt(),
                "## Working rules",
                "- Before invoking `tool_forge`, ALWAYS call `list_generated_tools` first — reuse over regeneration.",
                "- To spawn a specialist subagent, use `munin_wake` with a task JSON.",
                "- Escape LDAP filter parameters — call `ldap_search` with filter_template + params, never build raw filters.",
                "- Publish notable findings via `publish_shared_intel` so subagents share knowledge.",
                "- If uncertain, ask a clarifying question by responding without a tool call.",
                "- You can execute shell commands using `execute_command` in case you need something.",
                "- You can generate SVG or Mermaid code to provide graphical representations when requested (e.g. for Active Directory graphs or similar).",

            ]
        )

    # ------------------------------------------------------------------
    # Loop
    # ------------------------------------------------------------------
    #
    # ReAct iteration budget.
    #
    # By default there is NO fixed cap — the loop runs until the LLM stops calling
    # tools (natural termination) or MUNIN_MAX_ITERATIONS is set explicitly in the
    # environment. Callers can pass ``max_iterations=N`` per request to bound a
    # specific chat. The runaway-protection is a very high hard ceiling (10_000)
    # so a genuinely broken model can't spin the box forever, but for practical
    # offensive workflows this ceiling is unreachable.
    #
    # Tool results are NOT truncated when fed back to the LLM. If the model's
    # context is exceeded, the LLM API will report it — better than silently
    # hiding evidence the model needs (dump_domain_structure, cve_enrich, etc.).
    _HARD_CEILING = 10_000

    def respond(
        self,
        user_input: str,
        *,
        max_iterations: int | None = None,
        progress: Callable[[dict[str, Any]], None] | None = None,
    ) -> dict[str, Any]:
        import os
        import time

        if max_iterations is None:
            env_val = os.environ.get("MUNIN_MAX_ITERATIONS", "").strip()
            if env_val:
                try:
                    max_iterations = int(env_val)
                except ValueError:
                    max_iterations = self._HARD_CEILING
            else:
                max_iterations = self._HARD_CEILING  # effectively "no limit"

        messages: list[dict[str, Any]] = [
            {"role": "system", "content": self._system_prompt()},
            {"role": "user", "content": user_input.strip()},
        ]
        self.memory.log_step(agent="munin", action="user_input", input_data={"text": user_input}, tags=["dialog"])
        final_content = ""
        tool_calls_log: list[dict[str, Any]] = []
        stop_reason = "unknown"
        step = -1

        # Repetition guard — catches stuck ReAct loops.
        #
        # Two failure modes we defend against:
        #   (a) Same tool + same args, N times in a row. Classic "model can't
        #       decide what to do next".
        #   (b) Alternating loop A → B → A → B → A → B forever. The naive
        #       "same fingerprint N times consecutively" test misses this; we
        #       widen the window to WINDOW_SIZE and require the window to have
        #       fewer than MIN_UNIQUE distinct fingerprints to trip.
        #
        # Sizing: WINDOW_SIZE=6, MIN_UNIQUE=3 means "over the last 6 tool calls,
        # the model touched at most 2 distinct (tool,args) — that's a loop."
        # Legitimate exploration of a small space (e.g. querying LDAP for 3
        # different users) has ≥3 distinct fingerprints in any 6-call window.
        WINDOW_SIZE = 6
        MIN_UNIQUE = 3
        recent_calls: list[str] = []
        nudged_once = False

        def emit(event: dict[str, Any]) -> None:
            """Best-effort public execution telemetry for an async operator UI."""
            if progress is None:
                return
            try:
                progress(event)
            except Exception:  # telemetry must never derail the agent
                logger.debug("progress observer failed", exc_info=True)

        for step in range(max_iterations):
            catalog = self._current_catalog()
            specs = _tool_specs(catalog)
            emit({"stage": "reasoning", "iteration": step + 1, "message": "Requesting model response"})
            try:
                completion = self.llm.chat(messages=messages, tools=specs, temperature=0.2)
            except Exception as exc:  # noqa: BLE001
                logger.exception("LLM call failed at step %d", step)
                raise RuntimeError(f"LLM call failed at step {step}: {exc}") from exc
            message = completion["choices"][0]["message"]
            messages.append(message)
            content_now = (message.get("content") or "").strip()
            self.memory.log_step(
                agent="munin",
                action="react_step",
                input_data={"step": step},
                output_data={
                    "tool_calls": len(message.get("tool_calls") or []),
                    "content_snippet": content_now[:400],
                },
                tags=["react"],
            )
            tool_calls = message.get("tool_calls") or []
            if not tool_calls:
                # Natural stop — LLM has decided to speak instead of tool-call.
                final_content = content_now
                stop_reason = "final_answer"
                emit({"stage": "completed", "iteration": step + 1, "message": "Model returned a final response"})
                break

            # Keep the running content in case we hit the iteration cap mid-tool-loop —
            # then we can still return the last thing the LLM said, not just "(max reached)".
            if content_now:
                final_content = content_now

            # Track fingerprints for repetition detection.
            step_fingerprints: list[str] = []
            for call in tool_calls:
                tool_name = call["function"]["name"]
                try:
                    args = json.loads(call["function"].get("arguments") or "{}")
                except json.JSONDecodeError:
                    args = {}
                step_fingerprints.append(f"{tool_name}::{json.dumps(args, sort_keys=True, default=str)}")
                fn = catalog.get(tool_name)
                t0 = time.monotonic()
                emit({"stage": "tool_start", "iteration": step + 1, "tool": tool_name, "arguments": args})
                if not fn:
                    tool_result = {"ok": False, "error": {"code": "unknown_tool", "message": tool_name}}
                else:
                    try:
                        tool_result = fn(**args)
                    except TypeError as exc:
                        tool_result = {"ok": False, "error": {"code": "bad_args", "message": str(exc)}}
                    except Exception as exc:  # noqa: BLE001
                        logger.exception("tool %s crashed", tool_name)
                        tool_result = {"ok": False, "error": {"code": "tool_crashed", "message": str(exc)}}
                elapsed_ms = int((time.monotonic() - t0) * 1000)
                emit({
                    "stage": "tool_result",
                    "iteration": step + 1,
                    "tool": tool_name,
                    "ok": tool_result.get("ok", True),
                    "elapsed_ms": elapsed_ms,
                    "summary": tool_result.get("summary", ""),
                })
                self.memory.log_step(
                    agent="munin",
                    action=f"tool:{tool_name}",
                    input_data=args,
                    output_data={"ok": tool_result.get("ok"), "summary": tool_result.get("summary")},
                    tags=["tool"],
                )
                # Record for the caller (frontend tool-call cards) — untruncated.
                entry: dict[str, Any] = {
                    "name": tool_name,
                    "arguments": args,
                    "elapsed_ms": elapsed_ms,
                    "ok": tool_result.get("ok", True),
                    "summary": tool_result.get("summary", ""),
                }
                if tool_result.get("ok", True):
                    entry["result"] = tool_result.get("data", tool_result)
                else:
                    entry["error"] = tool_result.get("error", {"code": "error", "message": str(tool_result)})
                tool_calls_log.append(entry)
                # Feed FULL result back to LLM. If context becomes an issue, the LLM
                # itself will report it — better than silently hiding evidence.
                messages.append(
                    {
                        "role": "tool",
                        "tool_call_id": call["id"],
                        "name": tool_name,
                        "content": json.dumps(tool_result, ensure_ascii=True, default=str),
                    }
                )

            # Repetition guard — check AFTER executing this iteration's tool_calls.
            recent_calls.extend(step_fingerprints)
            if len(recent_calls) > WINDOW_SIZE:
                recent_calls = recent_calls[-WINDOW_SIZE:]

            # Trip when window is full AND has too few distinct fingerprints.
            # This catches both:
            #   - full identical repeats (unique_count = 1)
            #   - alternating A/B loops (unique_count = 2)
            unique_count = len(set(recent_calls))
            if len(recent_calls) >= WINDOW_SIZE and unique_count < MIN_UNIQUE:
                tools_seen = sorted({c.split("::")[0] for c in recent_calls})
                if not nudged_once:
                    logger.warning(
                        "repetition detected: last %d calls used only %d distinct fingerprint(s) across tools %s — nudging model",
                        len(recent_calls), unique_count, tools_seen,
                    )
                    messages.append(
                        {
                            "role": "system",
                            "content": (
                                f"NOTICE: over your last {len(recent_calls)} tool calls you only "
                                f"used {unique_count} distinct (tool, arguments) combination(s) "
                                f"({tools_seen}). You appear to be looping. Change your approach: "
                                "call a different tool, change the arguments substantively, or "
                                "produce your final answer if the evidence is sufficient."
                            ),
                        }
                    )
                    nudged_once = True
                    # Start a fresh observation window. A single substantively
                    # different next call now satisfies the nudge instead of
                    # being judged against five pre-nudge fingerprints.
                    recent_calls.clear()
                else:
                    logger.error("repetition persists after nudge — aborting loop")
                    stop_reason = "repetition_detected"
                    if not final_content:
                        final_content = (
                            f"(aborted after {step + 1} iterations — model looped on "
                            f"{tools_seen} despite a corrective nudge; unique fingerprints={unique_count})"
                        )
                    break
        else:
            # for-else: loop exhausted without a natural break.
            stop_reason = "max_iterations"
            if not final_content:
                final_content = (
                    f"(max iterations reached after {max_iterations} steps — "
                    f"executed {len(tool_calls_log)} tool calls; no final answer yet)"
                )

        # Persist a short marker but keep the full content in the response payload.
        self.memory.log_step(
            agent="munin",
            action="final_response",
            output_data={
                "content_length": len(final_content),
                "content_snippet": final_content[:2000],
                "stop_reason": stop_reason,
                "iterations": step + 1,
            },
            tags=["dialog"],
        )
        return {
            "content": final_content,
            "iterations": step + 1,
            "tool_calls": tool_calls_log,
            "stop_reason": stop_reason,
        }
