"""Dynamic MCP tool registry — hot-loads tools produced by `tool_forge`.

When `tool_forge` finishes generating and validating a Python script, we import the
callable and expose it as an MCP tool named ``gen__<slug>``. All generated tools live
under a common prefix so any MCP client can enumerate them. Metadata (name, description,
signature, tags, script path) persists in `procedural` table and is re-loaded on server
startup by :func:`rehydrate`.

This module also exposes :class:`ToolRegistry`, a stateful class-based interface used
by the LangGraph supervisor (PR-05 Tool Gateway, PR-06 Tool Factory).  The module-level
functions are kept for backward compatibility with the existing MCP surface.
"""

from __future__ import annotations

import importlib.util
import inspect
import json
import logging
import sqlite3
import sys
from pathlib import Path
from typing import Any, Callable

from .config import Settings, safe_slug
from .shared_state import SharedStateStore

logger = logging.getLogger("munin-mcp.registry")

GENERATED_PREFIX = "gen__"


class ToolRegistryError(RuntimeError):
    pass


def _load_callable(script_path: Path, function_name: str) -> Callable[..., Any]:
    if not script_path.exists():
        raise ToolRegistryError(f"script not found: {script_path}")
    module_name = f"munin_generated__{safe_slug([script_path.stem])}"
    spec = importlib.util.spec_from_file_location(module_name, str(script_path))
    if not spec or not spec.loader:
        raise ToolRegistryError(f"failed to build import spec for {script_path}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[module_name] = module
    spec.loader.exec_module(module)
    if not hasattr(module, function_name):
        raise ToolRegistryError(f"function '{function_name}' not found in {script_path}")
    obj = getattr(module, function_name)
    if not callable(obj):
        raise ToolRegistryError(f"'{function_name}' in {script_path} is not callable")
    return obj


def _tool_name(slug: str) -> str:
    slug = safe_slug([slug])
    return f"{GENERATED_PREFIX}{slug}"


def register(
    mcp: Any,
    state: SharedStateStore,
    *,
    slug: str,
    description: str,
    script_path: Path | str,
    function_name: str,
    signature: dict[str, Any],
    tags: list[str] | None = None,
    created_by_agent: str = "tool_forge",
) -> dict[str, Any]:
    """Register a generated tool: persist row + attach handler to MCP server."""
    tool_name = _tool_name(slug)
    script_path = Path(script_path).resolve()
    fn = _load_callable(script_path, function_name)
    sig = inspect.signature(fn)
    handler_doc = (description or fn.__doc__ or "").strip() or f"Autogenerated tool {tool_name}"

    def _handler(*args: Any, **kwargs: Any) -> dict[str, Any]:
        try:
            result = fn(*args, **kwargs)
            output = result if isinstance(result, dict) else {"result": result}
            state.episodic_record(
                agent="generated_tool_runtime",
                action=tool_name,
                input_data={"args": args, "kwargs": kwargs},
                output_data=output,
                tags=["autogenerated"],
            )
            return {"ok": True, "tool": tool_name, "mode": "sync", "summary": f"{tool_name} ran", "data": output}
        except Exception as exc:
            state.episodic_record(
                agent="generated_tool_runtime",
                action=tool_name,
                input_data={"args": args, "kwargs": kwargs},
                output_data={"error": str(exc)},
                tags=["autogenerated", "error"],
            )
            return {
                "ok": False,
                "tool": tool_name,
                "mode": "sync",
                "summary": f"{tool_name} failed",
                "error": {"code": "generated_tool_failed", "message": str(exc)},
            }

    _handler.__name__ = tool_name
    _handler.__doc__ = handler_doc
    _handler.__signature__ = sig  # type: ignore[attr-defined]

    try:
        mcp.tool()(_handler)
    except Exception as exc:  # pragma: no cover - guardrail
        raise ToolRegistryError(f"failed to attach {tool_name} to MCP server: {exc}") from exc

    state.procedural_register(
        name=tool_name,
        description=handler_doc,
        script_path=str(script_path),
        signature=signature,
        tags=tags or [],
        created_by_agent=created_by_agent,
    )
    logger.info("registered generated tool %s (%s)", tool_name, script_path)
    return {"name": tool_name, "script_path": str(script_path), "signature": signature, "tags": tags or []}


def rehydrate(mcp: Any, state: SharedStateStore, settings: Settings) -> int:
    """Re-attach every active generated tool at server startup."""
    active = state.procedural_list(include_inactive=False)
    count = 0
    for row in active:
        try:
            slug = row["name"].removeprefix(GENERATED_PREFIX)
            function_name = row["signature"].get("function_name") or row["signature"].get("name") or slug
            register(
                mcp,
                state,
                slug=slug,
                description=row.get("description", ""),
                script_path=row["script_path"],
                function_name=function_name,
                signature=row.get("signature", {}),
                tags=row.get("tags", []),
                created_by_agent=row.get("created_by_agent", "tool_forge"),
            )
            count += 1
        except Exception as exc:
            logger.warning("failed to rehydrate %s: %s", row.get("name"), exc)
    return count


def resolve_tool_by_name(state: SharedStateStore, name: str) -> dict[str, Any] | None:
    if not name.startswith(GENERATED_PREFIX):
        name = _tool_name(name)
    return state.procedural_get(name)


def list_generated(state: SharedStateStore, *, tag: str = "") -> list[dict[str, Any]]:
    return state.procedural_list(tag=tag, include_inactive=False)


def deactivate(state: SharedStateStore, name: str) -> bool:
    if not name.startswith(GENERATED_PREFIX):
        name = _tool_name(name)
    return state.procedural_deactivate(name)


def purge_all(state: SharedStateStore) -> int:
    """Purge every generated tool. Used by `munin reset`."""
    return state.procedural_purge_all()


def signature_to_json_schema(sig: inspect.Signature) -> dict[str, Any]:
    """Best-effort inspect.Signature → JSON schema. Used by tool_forge before persistence."""
    properties: dict[str, Any] = {}
    required: list[str] = []
    for name, param in sig.parameters.items():
        annotation = param.annotation if param.annotation is not inspect._empty else str
        json_type = "string"
        if annotation in (int,):
            json_type = "integer"
        elif annotation in (float,):
            json_type = "number"
        elif annotation in (bool,):
            json_type = "boolean"
        elif annotation in (list, tuple):
            json_type = "array"
        elif annotation in (dict,):
            json_type = "object"
        properties[name] = {"type": json_type}
        if param.default is inspect._empty:
            required.append(name)
        else:
            try:
                json.dumps(param.default)
                properties[name]["default"] = param.default
            except TypeError:
                pass
    return {"type": "object", "properties": properties, "required": required}


# ---------------------------------------------------------------------------
# ToolRegistry — class-based interface for LangGraph supervisor (PR-05/PR-06)
# ---------------------------------------------------------------------------

class ToolRegistry:
    """
    Stateful tool registry used by the LangGraph supervisor, Tool Gateway, and
    Tool Factory.  Backed by an in-memory dict plus an optional SQLite sidecar
    for provenance metadata.

    Unlike the module-level functions above (which are tied to a live
    ``SharedStateStore``), this class is self-contained and works without an
    MCP server instance.  It is the primary interface consumed by:

    - :mod:`munin.core.tool_gateway` — wraps tools as LangChain StructuredTools
    - :mod:`munin.core.autonomy.tool_factory` — creates and invokes gen__ tools
    """

    def __init__(self, db_path: str | None = None) -> None:
        # name → {description, handler, signature, active, state_only}
        self._tools: dict[str, dict[str, Any]] = {}
        self._db_path = db_path
        if db_path:
            self._init_db(db_path)

    # ------------------------------------------------------------------
    # Schema / DB helpers
    # ------------------------------------------------------------------

    def _init_db(self, db_path: str) -> None:
        con = sqlite3.connect(db_path)
        con.executescript(
            """
            CREATE TABLE IF NOT EXISTS tool_registry (
                name        TEXT PRIMARY KEY,
                description TEXT,
                signature   TEXT,
                state_only  INTEGER DEFAULT 0,
                active      INTEGER DEFAULT 1
            );
            CREATE TABLE IF NOT EXISTS tool_provenance (
                name              TEXT PRIMARY KEY,
                creator_agent     TEXT,
                parent_run        TEXT,
                spec              TEXT,
                source            TEXT,
                deps              TEXT,
                validation_results TEXT,
                created_at        TEXT DEFAULT (datetime('now'))
            );
            """
        )
        con.commit()
        con.close()

    def _db_upsert(self, name: str, description: str, signature: dict, state_only: bool, active: bool) -> None:
        if not self._db_path:
            return
        con = sqlite3.connect(self._db_path)
        con.execute(
            """
            INSERT INTO tool_registry (name, description, signature, state_only, active)
            VALUES (?, ?, ?, ?, ?)
            ON CONFLICT(name) DO UPDATE SET
                description=excluded.description,
                signature=excluded.signature,
                state_only=excluded.state_only,
                active=excluded.active
            """,
            (name, description, json.dumps(signature), int(state_only), int(active)),
        )
        con.commit()
        con.close()

    def _db_load_all(self) -> list[dict[str, Any]]:
        if not self._db_path:
            return []
        try:
            con = sqlite3.connect(self._db_path)
            rows = con.execute(
                "SELECT name, description, signature, state_only, active FROM tool_registry WHERE active=1"
            ).fetchall()
            con.close()
            return [
                {
                    "name": r[0],
                    "description": r[1],
                    "signature": json.loads(r[2]) if r[2] else {},
                    "state_only": bool(r[3]),
                    "active": bool(r[4]),
                }
                for r in rows
            ]
        except Exception as exc:
            logger.warning("ToolRegistry: failed to load from db: %s", exc)
            return []

    # ------------------------------------------------------------------
    # Public interface
    # ------------------------------------------------------------------

    def register(
        self,
        name: str,
        description: str,
        handler: Callable,
        signature: dict,
        *,
        state_only: bool = False,
        active: bool = True,
    ) -> None:
        """Register a tool.  gen__ prefix marks dynamically-generated tools."""
        self._tools[name] = {
            "name": name,
            "description": description,
            "handler": handler,
            "signature": signature,
            "state_only": state_only,
            "active": active,
        }
        self._db_upsert(name, description, signature, state_only, active)

    def register_state_only(
        self,
        name: str,
        description: str,
        handler: Callable,
        signature: dict,
    ) -> None:
        """Register a tool that only updates state, not invocable by LLM."""
        self.register(name, description, handler, signature, state_only=True)

    def rehydrate(self) -> list[dict]:
        """Return all active=1 tools from persistent storage (in-memory + DB)."""
        in_memory = [
            {k: v for k, v in entry.items() if k != "handler"}
            for entry in self._tools.values()
            if entry.get("active", True)
        ]
        if not in_memory and self._db_path:
            return self._db_load_all()
        return in_memory

    def get_openai_schema(self, name: str) -> dict:
        """Return OpenAI-compatible function schema for a tool."""
        entry = self._tools.get(name)
        if not entry:
            raise KeyError(f"Tool {name!r} not registered")
        sig = entry["signature"]
        return {
            "type": "function",
            "function": {
                "name": name,
                "description": entry["description"],
                "parameters": sig,
            },
        }

    def get_handler(self, name: str) -> Callable | None:
        """Return the callable for a registered tool, or None if not found."""
        entry = self._tools.get(name)
        if entry:
            return entry.get("handler")
        return None

    def iter_signature_specs(self):
        """
        Yield (name, description, signature_dict, handler) for all active,
        non-state-only tools.

        Used by Tool Gateway to wrap tools as LangChain StructuredTools.
        """
        for entry in self._tools.values():
            if not entry.get("active", True):
                continue
            if entry.get("state_only", False):
                continue
            handler = entry.get("handler")
            if handler is None:
                continue
            yield (
                entry["name"],
                entry["description"],
                entry["signature"],
                handler,
            )

    def record_provenance(
        self,
        name: str,
        creator_agent: str,
        parent_run: str,
        spec: str,
        source: str,
        deps: list[str],
        validation_results: list[dict],
    ) -> None:
        """Record provenance metadata for a dynamically-created tool."""
        if self._db_path:
            try:
                con = sqlite3.connect(self._db_path)
                con.execute(
                    """
                    INSERT INTO tool_provenance
                        (name, creator_agent, parent_run, spec, source, deps, validation_results)
                    VALUES (?, ?, ?, ?, ?, ?, ?)
                    ON CONFLICT(name) DO UPDATE SET
                        creator_agent=excluded.creator_agent,
                        parent_run=excluded.parent_run,
                        spec=excluded.spec,
                        source=excluded.source,
                        deps=excluded.deps,
                        validation_results=excluded.validation_results
                    """,
                    (
                        name,
                        creator_agent,
                        parent_run,
                        spec,
                        source,
                        json.dumps(deps),
                        json.dumps(validation_results),
                    ),
                )
                con.commit()
                con.close()
            except Exception as exc:
                logger.warning("ToolRegistry: failed to record provenance for %r: %s", name, exc)

        # Also annotate the in-memory entry
        if name in self._tools:
            self._tools[name]["provenance"] = {
                "creator_agent": creator_agent,
                "parent_run": parent_run,
                "spec": spec,
                "source": source,
                "deps": deps,
                "validation_results": validation_results,
            }
