"""Dynamic MCP tool registry — hot-loads tools produced by `tool_forge`.

When `tool_forge` finishes generating and validating a Python script, we import the
callable and expose it as an MCP tool named ``gen__<slug>``. All generated tools live
under a common prefix so any MCP client can enumerate them. Metadata (name, description,
signature, tags, script path) persists in `procedural` table and is re-loaded on server
startup by :func:`rehydrate`.
"""

from __future__ import annotations

import importlib.util
import inspect
import json
import logging
import sys
from pathlib import Path
from typing import Any, Callable

from .config import Settings, safe_slug
from .shared_state import SharedStateStore

logger = logging.getLogger("munin-mcp.registry")

GENERATED_PREFIX = "gen__"


class ToolRegistryError(RuntimeError):
    pass


def _load_callable(script_path: Path, function_name: str) -> Callable[..., Any]:
    if not script_path.exists():
        raise ToolRegistryError(f"script not found: {script_path}")
    module_name = f"munin_generated__{safe_slug([script_path.stem])}"
    spec = importlib.util.spec_from_file_location(module_name, str(script_path))
    if not spec or not spec.loader:
        raise ToolRegistryError(f"failed to build import spec for {script_path}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[module_name] = module
    spec.loader.exec_module(module)
    if not hasattr(module, function_name):
        raise ToolRegistryError(f"function '{function_name}' not found in {script_path}")
    obj = getattr(module, function_name)
    if not callable(obj):
        raise ToolRegistryError(f"'{function_name}' in {script_path} is not callable")
    return obj


def _tool_name(slug: str) -> str:
    slug = safe_slug([slug])
    return f"{GENERATED_PREFIX}{slug}"


def register(
    mcp: Any,
    state: SharedStateStore,
    *,
    slug: str,
    description: str,
    script_path: Path | str,
    function_name: str,
    signature: dict[str, Any],
    tags: list[str] | None = None,
    created_by_agent: str = "tool_forge",
) -> dict[str, Any]:
    """Register a generated tool: persist row + attach handler to MCP server."""
    tool_name = _tool_name(slug)
    script_path = Path(script_path).resolve()
    fn = _load_callable(script_path, function_name)
    sig = inspect.signature(fn)
    handler_doc = (description or fn.__doc__ or "").strip() or f"Autogenerated tool {tool_name}"

    def _handler(*args: Any, **kwargs: Any) -> dict[str, Any]:
        try:
            result = fn(*args, **kwargs)
            output = result if isinstance(result, dict) else {"result": result}
            state.episodic_record(
                agent="generated_tool_runtime",
                action=tool_name,
                input_data={"args": args, "kwargs": kwargs},
                output_data=output,
                tags=["autogenerated"],
            )
            return {"ok": True, "tool": tool_name, "mode": "sync", "summary": f"{tool_name} ran", "data": output}
        except Exception as exc:
            state.episodic_record(
                agent="generated_tool_runtime",
                action=tool_name,
                input_data={"args": args, "kwargs": kwargs},
                output_data={"error": str(exc)},
                tags=["autogenerated", "error"],
            )
            return {
                "ok": False,
                "tool": tool_name,
                "mode": "sync",
                "summary": f"{tool_name} failed",
                "error": {"code": "generated_tool_failed", "message": str(exc)},
            }

    _handler.__name__ = tool_name
    _handler.__doc__ = handler_doc
    _handler.__signature__ = sig  # type: ignore[attr-defined]

    try:
        mcp.tool()(_handler)
    except Exception as exc:  # pragma: no cover - guardrail
        raise ToolRegistryError(f"failed to attach {tool_name} to MCP server: {exc}") from exc

    state.procedural_register(
        name=tool_name,
        description=handler_doc,
        script_path=str(script_path),
        signature=signature,
        tags=tags or [],
        created_by_agent=created_by_agent,
    )
    logger.info("registered generated tool %s (%s)", tool_name, script_path)
    return {"name": tool_name, "script_path": str(script_path), "signature": signature, "tags": tags or []}


def rehydrate(mcp: Any, state: SharedStateStore, settings: Settings) -> int:
    """Re-attach every active generated tool at server startup."""
    active = state.procedural_list(include_inactive=False)
    count = 0
    for row in active:
        try:
            slug = row["name"].removeprefix(GENERATED_PREFIX)
            function_name = row["signature"].get("function_name") or row["signature"].get("name") or slug
            register(
                mcp,
                state,
                slug=slug,
                description=row.get("description", ""),
                script_path=row["script_path"],
                function_name=function_name,
                signature=row.get("signature", {}),
                tags=row.get("tags", []),
                created_by_agent=row.get("created_by_agent", "tool_forge"),
            )
            count += 1
        except Exception as exc:
            logger.warning("failed to rehydrate %s: %s", row.get("name"), exc)
    return count


def resolve_tool_by_name(state: SharedStateStore, name: str) -> dict[str, Any] | None:
    if not name.startswith(GENERATED_PREFIX):
        name = _tool_name(name)
    return state.procedural_get(name)


def list_generated(state: SharedStateStore, *, tag: str = "") -> list[dict[str, Any]]:
    return state.procedural_list(tag=tag, include_inactive=False)


def deactivate(state: SharedStateStore, name: str) -> bool:
    if not name.startswith(GENERATED_PREFIX):
        name = _tool_name(name)
    return state.procedural_deactivate(name)


def purge_all(state: SharedStateStore) -> int:
    """Purge every generated tool. Used by `munin reset`."""
    return state.procedural_purge_all()


def signature_to_json_schema(sig: inspect.Signature) -> dict[str, Any]:
    """Best-effort inspect.Signature → JSON schema. Used by tool_forge before persistence."""
    properties: dict[str, Any] = {}
    required: list[str] = []
    for name, param in sig.parameters.items():
        annotation = param.annotation if param.annotation is not inspect._empty else str
        json_type = "string"
        if annotation in (int,):
            json_type = "integer"
        elif annotation in (float,):
            json_type = "number"
        elif annotation in (bool,):
            json_type = "boolean"
        elif annotation in (list, tuple):
            json_type = "array"
        elif annotation in (dict,):
            json_type = "object"
        properties[name] = {"type": json_type}
        if param.default is inspect._empty:
            required.append(name)
        else:
            try:
                json.dumps(param.default)
                properties[name]["default"] = param.default
            except TypeError:
                pass
    return {"type": "object", "properties": properties, "required": required}
