from __future__ import annotations

import json
import sqlite3
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any

from .config import Settings
from .utils import ensure_parent


def _utc_now() -> datetime:
    return datetime.now(timezone.utc)


def _utc_now_db() -> str:
    return _utc_now().replace(microsecond=0).isoformat().replace("+00:00", "Z")


def _lease_until(seconds: int) -> str:
    return (_utc_now() + timedelta(seconds=seconds)).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def _normalize_jsonish(raw: str) -> Any:
    text = (raw or "").strip()
    if not text:
        return {}
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        return {"raw": text}


def _normalize_tags(raw: str) -> list[str]:
    tags: list[str] = []
    for item in (raw or "").replace(",", "\n").splitlines():
        value = item.strip()
        if value:
            tags.append(value)
    return tags


@dataclass(frozen=True)
class SharedTaskDecision:
    success: bool
    message: str
    task_id: int | None = None
    stolen_stale_task_id: int | None = None


class SharedStateStore:
    """SQLite-backed shared state used by ALL Munin agents.

    Tables:
      - shared_intel        (OFFX original) findings shared across agents
      - active_tasks        (OFFX original) exclusive task locks with leases
      - agent_presence      (OFFX original) wake/sleep registry
      - agent_messages      (OFFX original) inter-agent inbox
      - episodic            (Munin new)     every tool call, ReAct step, decision
      - semantic            (Munin new)     facts Munin remembers
      - procedural          (Munin new)     autogenerated tools registry
      - generated_graphs    (Munin new)     forged ReAct graph specs
      - agent_wake_queue    (Munin new)     orchestrator → subagent wake channel
    """

    def __init__(self, settings: Settings) -> None:
        self.settings = settings
        self.db_path = settings.shared_state_db
        ensure_parent(self.db_path)
        self._init_db()

    # ------------------------------------------------------------------
    # Connection / schema
    # ------------------------------------------------------------------
    def _connect(self) -> sqlite3.Connection:
        conn = sqlite3.connect(str(self.db_path), timeout=30)
        conn.row_factory = sqlite3.Row
        conn.execute("PRAGMA journal_mode=WAL")
        conn.execute("PRAGMA synchronous=NORMAL")
        conn.execute("PRAGMA foreign_keys=ON")
        conn.execute("PRAGMA busy_timeout=30000")
        return conn

    def _init_db(self) -> None:
        with self._connect() as conn:
            conn.executescript(
                """
                -- OFFX-original tables
                CREATE TABLE IF NOT EXISTS shared_intel (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    target_ip TEXT NOT NULL,
                    port INTEGER,
                    service TEXT,
                    finding_type TEXT NOT NULL,
                    severity TEXT,
                    details TEXT NOT NULL DEFAULT '{}',
                    source_agent TEXT,
                    status TEXT NOT NULL DEFAULT 'NEW',
                    tags TEXT NOT NULL DEFAULT '[]',
                    fingerprint TEXT NOT NULL DEFAULT '',
                    timestamp TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
                );

                CREATE TABLE IF NOT EXISTS active_tasks (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    target_ip TEXT NOT NULL,
                    action TEXT NOT NULL,
                    task_key TEXT NOT NULL,
                    assigned_agent TEXT NOT NULL,
                    status TEXT NOT NULL,
                    lease_expires_at TEXT NOT NULL,
                    metadata TEXT NOT NULL DEFAULT '{}',
                    result TEXT NOT NULL DEFAULT '{}',
                    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
                );

                CREATE TABLE IF NOT EXISTS agent_presence (
                    agent_name TEXT PRIMARY KEY,
                    role TEXT NOT NULL DEFAULT '',
                    status TEXT NOT NULL DEFAULT 'IDLE',
                    current_task_id INTEGER,
                    last_seen_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    metadata TEXT NOT NULL DEFAULT '{}',
                    FOREIGN KEY(current_task_id) REFERENCES active_tasks(id)
                );

                CREATE TABLE IF NOT EXISTS agent_messages (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    sender_agent TEXT NOT NULL,
                    recipient_agent TEXT NOT NULL,
                    subject TEXT NOT NULL DEFAULT '',
                    message_type TEXT NOT NULL DEFAULT 'INFO',
                    body TEXT NOT NULL DEFAULT '',
                    related_task_id INTEGER,
                    related_target_ip TEXT NOT NULL DEFAULT '',
                    status TEXT NOT NULL DEFAULT 'NEW',
                    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    read_at TEXT NOT NULL DEFAULT '',
                    metadata TEXT NOT NULL DEFAULT '{}',
                    FOREIGN KEY(related_task_id) REFERENCES active_tasks(id)
                );

                -- Munin-new tables
                CREATE TABLE IF NOT EXISTS episodic (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    ts TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    agent TEXT NOT NULL,
                    action TEXT NOT NULL,
                    input_json TEXT NOT NULL DEFAULT '{}',
                    output_json TEXT NOT NULL DEFAULT '{}',
                    tags TEXT NOT NULL DEFAULT '[]'
                );

                CREATE TABLE IF NOT EXISTS semantic (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    key TEXT NOT NULL UNIQUE,
                    value_json TEXT NOT NULL DEFAULT '{}',
                    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
                );

                CREATE TABLE IF NOT EXISTS procedural (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    name TEXT NOT NULL UNIQUE,
                    description TEXT NOT NULL DEFAULT '',
                    script_path TEXT NOT NULL,
                    signature_json TEXT NOT NULL DEFAULT '{}',
                    tags TEXT NOT NULL DEFAULT '[]',
                    created_by_agent TEXT NOT NULL DEFAULT '',
                    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    active INTEGER NOT NULL DEFAULT 1
                );

                CREATE TABLE IF NOT EXISTS generated_graphs (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    name TEXT NOT NULL UNIQUE,
                    purpose TEXT NOT NULL DEFAULT '',
                    system_prompt TEXT NOT NULL DEFAULT '',
                    tool_whitelist_json TEXT NOT NULL DEFAULT '[]',
                    reset_policy TEXT NOT NULL DEFAULT 'on_reset',
                    created_by_agent TEXT NOT NULL DEFAULT '',
                    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    active INTEGER NOT NULL DEFAULT 1
                );

                CREATE TABLE IF NOT EXISTS agent_wake_queue (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    target_agent TEXT NOT NULL,
                    task_json TEXT NOT NULL DEFAULT '{}',
                    priority INTEGER NOT NULL DEFAULT 0,
                    enqueued_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    claimed_at TEXT NOT NULL DEFAULT '',
                    claimer_pid INTEGER
                );

                -- Indexes
                CREATE INDEX IF NOT EXISTS idx_shared_intel_target ON shared_intel(target_ip);
                CREATE INDEX IF NOT EXISTS idx_shared_intel_service ON shared_intel(service);
                CREATE INDEX IF NOT EXISTS idx_shared_intel_type ON shared_intel(finding_type);
                CREATE INDEX IF NOT EXISTS idx_active_tasks_target ON active_tasks(target_ip);
                CREATE INDEX IF NOT EXISTS idx_active_tasks_agent ON active_tasks(assigned_agent);
                CREATE INDEX IF NOT EXISTS idx_agent_messages_recipient ON agent_messages(recipient_agent, status, created_at);
                CREATE INDEX IF NOT EXISTS idx_agent_messages_task ON agent_messages(related_task_id);
                CREATE UNIQUE INDEX IF NOT EXISTS ux_active_task_running
                    ON active_tasks(task_key)
                    WHERE status = 'RUNNING';

                CREATE INDEX IF NOT EXISTS idx_episodic_agent_ts ON episodic(agent, ts DESC);
                CREATE INDEX IF NOT EXISTS idx_episodic_action ON episodic(action);
                CREATE INDEX IF NOT EXISTS idx_procedural_name ON procedural(name);
                CREATE INDEX IF NOT EXISTS idx_procedural_active ON procedural(active);
                CREATE INDEX IF NOT EXISTS idx_generated_graphs_active ON generated_graphs(active);
                CREATE INDEX IF NOT EXISTS idx_agent_wake_queue_target ON agent_wake_queue(target_agent, claimed_at);
                """
            )

    # ------------------------------------------------------------------
    # shared_intel (unchanged)
    # ------------------------------------------------------------------
    def publish_intel(
        self,
        *,
        target_ip: str,
        port: int | None,
        service: str,
        finding_type: str,
        severity: str,
        details_json: str,
        source_agent: str,
        status: str,
        tags: str,
        fingerprint: str,
    ) -> dict[str, Any]:
        now = _utc_now_db()
        details = _normalize_jsonish(details_json)
        tag_list = _normalize_tags(tags)
        with self._connect() as conn:
            cursor = conn.execute(
                """
                INSERT INTO shared_intel (
                    target_ip, port, service, finding_type, severity, details,
                    source_agent, status, tags, fingerprint, timestamp, updated_at
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                """,
                (
                    target_ip.strip(),
                    port,
                    service.strip(),
                    finding_type.strip(),
                    severity.strip() or "INFO",
                    json.dumps(details, ensure_ascii=True),
                    source_agent.strip(),
                    status.strip() or "NEW",
                    json.dumps(tag_list, ensure_ascii=True),
                    fingerprint.strip(),
                    now,
                    now,
                ),
            )
            intel_id = int(cursor.lastrowid)
        return {
            "intel_id": intel_id,
            "target_ip": target_ip.strip(),
            "finding_type": finding_type.strip(),
            "service": service.strip(),
            "severity": severity.strip() or "INFO",
            "source_agent": source_agent.strip(),
            "status": status.strip() or "NEW",
            "tags": tag_list,
            "timestamp": now,
        }

    def query_intel(
        self,
        *,
        target_ip: str = "",
        service: str = "",
        finding_type: str = "",
        severity: str = "",
        status: str = "",
        limit: int = 50,
    ) -> list[dict[str, Any]]:
        query = "SELECT * FROM shared_intel WHERE 1=1"
        params: list[Any] = []
        if target_ip.strip():
            query += " AND target_ip = ?"
            params.append(target_ip.strip())
        if service.strip():
            query += " AND service = ?"
            params.append(service.strip())
        if finding_type.strip():
            query += " AND finding_type = ?"
            params.append(finding_type.strip())
        if severity.strip():
            query += " AND severity = ?"
            params.append(severity.strip())
        if status.strip():
            query += " AND status = ?"
            params.append(status.strip())
        query += " ORDER BY timestamp DESC LIMIT ?"
        params.append(max(1, min(limit, 500)))
        with self._connect() as conn:
            rows = conn.execute(query, params).fetchall()
        return [self._intel_row_to_dict(row) for row in rows]

    # ------------------------------------------------------------------
    # active_tasks (unchanged)
    # ------------------------------------------------------------------
    def claim_task(
        self,
        *,
        target_ip: str,
        action: str,
        assigned_agent: str,
        lease_seconds: int,
        metadata_json: str,
        allow_steal_stale: bool,
    ) -> SharedTaskDecision:
        now = _utc_now_db()
        task_key = self._task_key(target_ip, action)
        metadata = _normalize_jsonish(metadata_json)
        with self._connect() as conn:
            conn.execute("BEGIN IMMEDIATE")
            row = conn.execute(
                """
                SELECT id, assigned_agent, lease_expires_at
                FROM active_tasks
                WHERE task_key = ? AND status = 'RUNNING'
                """,
                (task_key,),
            ).fetchone()
            stolen_task_id: int | None = None
            if row:
                lease_expires_at = row["lease_expires_at"] or ""
                stale = bool(lease_expires_at and lease_expires_at < now)
                if not stale or not allow_steal_stale:
                    conn.rollback()
                    return SharedTaskDecision(
                        success=False,
                        message=f"task already running for {task_key} by {row['assigned_agent']}",
                    )
                stolen_task_id = int(row["id"])
                conn.execute(
                    """
                    UPDATE active_tasks
                    SET status = 'STALE', updated_at = ?, result = ?
                    WHERE id = ?
                    """,
                    (
                        now,
                        json.dumps({"reason": "stolen_after_stale_lease"}, ensure_ascii=True),
                        stolen_task_id,
                    ),
                )
            cursor = conn.execute(
                """
                INSERT INTO active_tasks (
                    target_ip, action, task_key, assigned_agent, status,
                    lease_expires_at, metadata, result, created_at, updated_at
                ) VALUES (?, ?, ?, ?, 'RUNNING', ?, ?, '{}', ?, ?)
                """,
                (
                    target_ip.strip(),
                    action.strip(),
                    task_key,
                    assigned_agent.strip(),
                    _lease_until(max(30, lease_seconds)),
                    json.dumps(metadata, ensure_ascii=True),
                    now,
                    now,
                ),
            )
            task_id = int(cursor.lastrowid)
            conn.commit()
        return SharedTaskDecision(
            success=True,
            message=f"task claimed by {assigned_agent.strip()}",
            task_id=task_id,
            stolen_stale_task_id=stolen_task_id,
        )

    def heartbeat_task(self, *, task_id: int, assigned_agent: str, lease_seconds: int) -> dict[str, Any]:
        now = _utc_now_db()
        with self._connect() as conn:
            row = conn.execute(
                "SELECT id, assigned_agent, status FROM active_tasks WHERE id = ?",
                (task_id,),
            ).fetchone()
            if not row:
                return {"success": False, "message": f"task {task_id} not found"}
            if row["assigned_agent"] != assigned_agent.strip():
                return {"success": False, "message": f"task {task_id} owned by {row['assigned_agent']}"}
            if row["status"] != "RUNNING":
                return {"success": False, "message": f"task {task_id} is {row['status']}"}
            lease_expires_at = _lease_until(max(30, lease_seconds))
            conn.execute(
                "UPDATE active_tasks SET lease_expires_at = ?, updated_at = ? WHERE id = ?",
                (lease_expires_at, now, task_id),
            )
        return {"success": True, "message": "heartbeat updated", "task_id": task_id, "lease_expires_at": lease_expires_at}

    def complete_task(self, *, task_id: int, assigned_agent: str, status: str, result_json: str) -> dict[str, Any]:
        final_status = status.strip().upper() or "COMPLETED"
        if final_status not in {"COMPLETED", "FAILED", "CANCELLED"}:
            final_status = "COMPLETED"
        now = _utc_now_db()
        with self._connect() as conn:
            row = conn.execute("SELECT id, assigned_agent FROM active_tasks WHERE id = ?", (task_id,)).fetchone()
            if not row:
                return {"success": False, "message": f"task {task_id} not found"}
            if row["assigned_agent"] != assigned_agent.strip():
                return {"success": False, "message": f"task {task_id} owned by {row['assigned_agent']}"}
            conn.execute(
                "UPDATE active_tasks SET status = ?, result = ?, updated_at = ?, lease_expires_at = ? WHERE id = ?",
                (
                    final_status,
                    json.dumps(_normalize_jsonish(result_json), ensure_ascii=True),
                    now,
                    now,
                    task_id,
                ),
            )
        return {"success": True, "message": f"task {task_id} marked {final_status}", "task_id": task_id, "status": final_status}

    def list_tasks(self, *, status: str = "", assigned_agent: str = "", target_ip: str = "", limit: int = 100) -> list[dict[str, Any]]:
        query = "SELECT * FROM active_tasks WHERE 1=1"
        params: list[Any] = []
        if status.strip():
            query += " AND status = ?"
            params.append(status.strip().upper())
        if assigned_agent.strip():
            query += " AND assigned_agent = ?"
            params.append(assigned_agent.strip())
        if target_ip.strip():
            query += " AND target_ip = ?"
            params.append(target_ip.strip())
        query += " ORDER BY updated_at DESC LIMIT ?"
        params.append(max(1, min(limit, 500)))
        with self._connect() as conn:
            rows = conn.execute(query, params).fetchall()
        return [self._task_row_to_dict(row) for row in rows]

    def upsert_presence(
        self,
        *,
        agent_name: str,
        role: str,
        status: str,
        current_task_id: int | None,
        metadata_json: str,
    ) -> dict[str, Any]:
        now = _utc_now_db()
        metadata = _normalize_jsonish(metadata_json)
        with self._connect() as conn:
            conn.execute(
                """
                INSERT INTO agent_presence (agent_name, role, status, current_task_id, last_seen_at, metadata)
                VALUES (?, ?, ?, ?, ?, ?)
                ON CONFLICT(agent_name) DO UPDATE SET
                    role = excluded.role,
                    status = excluded.status,
                    current_task_id = excluded.current_task_id,
                    last_seen_at = excluded.last_seen_at,
                    metadata = excluded.metadata
                """,
                (
                    agent_name.strip(),
                    role.strip(),
                    status.strip().upper() or "IDLE",
                    current_task_id,
                    now,
                    json.dumps(metadata, ensure_ascii=True),
                ),
            )
        return {
            "agent_name": agent_name.strip(),
            "role": role.strip(),
            "status": status.strip().upper() or "IDLE",
            "current_task_id": current_task_id,
            "last_seen_at": now,
            "metadata": metadata,
        }

    def list_presence(self, *, stale_after_seconds: int = 3600) -> list[dict[str, Any]]:
        with self._connect() as conn:
            rows = conn.execute("SELECT * FROM agent_presence ORDER BY last_seen_at DESC").fetchall()
        now = _utc_now()
        matches: list[dict[str, Any]] = []
        for row in rows:
            last_seen_raw = row["last_seen_at"] or ""
            is_stale = False
            if last_seen_raw:
                parsed = datetime.fromisoformat(last_seen_raw.replace("Z", "+00:00"))
                is_stale = (now - parsed).total_seconds() > stale_after_seconds
            matches.append(
                {
                    "agent_name": row["agent_name"],
                    "role": row["role"],
                    "status": row["status"],
                    "current_task_id": row["current_task_id"],
                    "last_seen_at": row["last_seen_at"],
                    "metadata": _normalize_jsonish(row["metadata"] or "{}"),
                    "is_stale": is_stale,
                }
            )
        return matches

    def post_message(
        self,
        *,
        sender_agent: str,
        recipient_agent: str,
        subject: str,
        message_type: str,
        body: str,
        related_task_id: int | None,
        related_target_ip: str,
        metadata_json: str,
    ) -> dict[str, Any]:
        now = _utc_now_db()
        metadata = _normalize_jsonish(metadata_json)
        with self._connect() as conn:
            cursor = conn.execute(
                """
                INSERT INTO agent_messages (
                    sender_agent, recipient_agent, subject, message_type, body,
                    related_task_id, related_target_ip, status, created_at, read_at, metadata
                ) VALUES (?, ?, ?, ?, ?, ?, ?, 'NEW', ?, '', ?)
                """,
                (
                    sender_agent.strip(),
                    recipient_agent.strip(),
                    subject.strip(),
                    message_type.strip().upper() or "INFO",
                    body,
                    related_task_id,
                    related_target_ip.strip(),
                    now,
                    json.dumps(metadata, ensure_ascii=True),
                ),
            )
            message_id = int(cursor.lastrowid)
        return {
            "message_id": message_id,
            "sender_agent": sender_agent.strip(),
            "recipient_agent": recipient_agent.strip(),
            "subject": subject.strip(),
            "message_type": message_type.strip().upper() or "INFO",
            "related_task_id": related_task_id,
            "related_target_ip": related_target_ip.strip(),
            "status": "NEW",
            "created_at": now,
        }

    def fetch_messages(
        self,
        *,
        recipient_agent: str,
        status: str = "",
        message_type: str = "",
        mark_read: bool = False,
        limit: int = 50,
    ) -> list[dict[str, Any]]:
        query = "SELECT * FROM agent_messages WHERE recipient_agent = ?"
        params: list[Any] = [recipient_agent.strip()]
        if status.strip():
            query += " AND status = ?"
            params.append(status.strip().upper())
        if message_type.strip():
            query += " AND message_type = ?"
            params.append(message_type.strip().upper())
        query += " ORDER BY created_at DESC LIMIT ?"
        params.append(max(1, min(limit, 500)))
        with self._connect() as conn:
            rows = conn.execute(query, params).fetchall()
            matches = [self._message_row_to_dict(row) for row in rows]
            if mark_read and matches:
                now = _utc_now_db()
                ids = [row["id"] for row in rows]
                placeholders = ",".join("?" for _ in ids)
                conn.execute(
                    f"UPDATE agent_messages SET status = 'READ', read_at = ? WHERE id IN ({placeholders})",
                    [now, *ids],
                )
                for item in matches:
                    item["status"] = "READ"
                    item["read_at"] = now
        return matches

    def ack_message(self, *, message_id: int, recipient_agent: str, status: str) -> dict[str, Any]:
        final_status = status.strip().upper() or "ACKED"
        if final_status not in {"READ", "ACKED", "DONE"}:
            final_status = "ACKED"
        now = _utc_now_db()
        with self._connect() as conn:
            row = conn.execute(
                "SELECT id, recipient_agent FROM agent_messages WHERE id = ?",
                (message_id,),
            ).fetchone()
            if not row:
                return {"success": False, "message": f"message {message_id} not found"}
            if row["recipient_agent"] != recipient_agent.strip():
                return {"success": False, "message": f"message {message_id} belongs to {row['recipient_agent']}"}
            conn.execute(
                "UPDATE agent_messages SET status = ?, read_at = ? WHERE id = ?",
                (final_status, now, message_id),
            )
        return {"success": True, "message": f"message {message_id} marked {final_status}", "message_id": message_id, "status": final_status}

    def overview(self) -> dict[str, Any]:
        with self._connect() as conn:
            intel_count = conn.execute("SELECT COUNT(*) FROM shared_intel").fetchone()[0]
            new_count = conn.execute("SELECT COUNT(*) FROM shared_intel WHERE status = 'NEW'").fetchone()[0]
            running_count = conn.execute("SELECT COUNT(*) FROM active_tasks WHERE status = 'RUNNING'").fetchone()[0]
            stale_count = conn.execute("SELECT COUNT(*) FROM active_tasks WHERE status = 'STALE'").fetchone()[0]
            presence_count = conn.execute("SELECT COUNT(*) FROM agent_presence").fetchone()[0]
            unread_messages = conn.execute("SELECT COUNT(*) FROM agent_messages WHERE status = 'NEW'").fetchone()[0]
            episodic_count = conn.execute("SELECT COUNT(*) FROM episodic").fetchone()[0]
            semantic_count = conn.execute("SELECT COUNT(*) FROM semantic").fetchone()[0]
            procedural_count = conn.execute("SELECT COUNT(*) FROM procedural WHERE active=1").fetchone()[0]
            graphs_count = conn.execute("SELECT COUNT(*) FROM generated_graphs WHERE active=1").fetchone()[0]
            by_severity_rows = conn.execute(
                "SELECT COALESCE(severity, 'UNKNOWN') AS severity, COUNT(*) AS total FROM shared_intel GROUP BY COALESCE(severity, 'UNKNOWN')"
            ).fetchall()
        return {
            "db_path": str(self.db_path),
            "intel_total": intel_count,
            "intel_new": new_count,
            "tasks_running": running_count,
            "tasks_stale": stale_count,
            "agents_known": presence_count,
            "messages_unread": unread_messages,
            "episodic_rows": episodic_count,
            "semantic_rows": semantic_count,
            "generated_tools_active": procedural_count,
            "generated_graphs_active": graphs_count,
            "by_severity": {row["severity"]: row["total"] for row in by_severity_rows},
        }

    # ==================================================================
    # Munin extensions
    # ==================================================================

    # ---- episodic ----
    def episodic_record(
        self,
        *,
        agent: str,
        action: str,
        input_data: Any = None,
        output_data: Any = None,
        tags: list[str] | None = None,
    ) -> int:
        with self._connect() as conn:
            cursor = conn.execute(
                "INSERT INTO episodic (agent, action, input_json, output_json, tags) VALUES (?, ?, ?, ?, ?)",
                (
                    agent.strip(),
                    action.strip(),
                    json.dumps(input_data if input_data is not None else {}, ensure_ascii=True, default=str),
                    json.dumps(output_data if output_data is not None else {}, ensure_ascii=True, default=str),
                    json.dumps(tags or [], ensure_ascii=True),
                ),
            )
            return int(cursor.lastrowid)

    def episodic_query(self, *, agent: str = "", action: str = "", limit: int = 100) -> list[dict[str, Any]]:
        query = "SELECT * FROM episodic WHERE 1=1"
        params: list[Any] = []
        if agent.strip():
            query += " AND agent = ?"
            params.append(agent.strip())
        if action.strip():
            query += " AND action = ?"
            params.append(action.strip())
        query += " ORDER BY id DESC LIMIT ?"
        params.append(max(1, min(limit, 1000)))
        with self._connect() as conn:
            rows = conn.execute(query, params).fetchall()
        return [
            {
                "id": row["id"],
                "ts": row["ts"],
                "agent": row["agent"],
                "action": row["action"],
                "input": _normalize_jsonish(row["input_json"] or "{}"),
                "output": _normalize_jsonish(row["output_json"] or "{}"),
                "tags": _normalize_jsonish(row["tags"] or "[]"),
            }
            for row in rows
        ]

    # ---- semantic ----
    def semantic_remember(self, key: str, value: Any) -> dict[str, Any]:
        now = _utc_now_db()
        with self._connect() as conn:
            conn.execute(
                """
                INSERT INTO semantic (key, value_json, updated_at) VALUES (?, ?, ?)
                ON CONFLICT(key) DO UPDATE SET value_json = excluded.value_json, updated_at = excluded.updated_at
                """,
                (key.strip(), json.dumps(value, ensure_ascii=True, default=str), now),
            )
        return {"key": key.strip(), "updated_at": now}

    def semantic_recall(self, key: str) -> Any:
        with self._connect() as conn:
            row = conn.execute("SELECT value_json FROM semantic WHERE key = ?", (key.strip(),)).fetchone()
        return _normalize_jsonish(row["value_json"]) if row else None

    def semantic_list(self, *, prefix: str = "", limit: int = 200) -> list[dict[str, Any]]:
        query = "SELECT * FROM semantic"
        params: list[Any] = []
        if prefix.strip():
            query += " WHERE key LIKE ?"
            params.append(f"{prefix.strip()}%")
        query += " ORDER BY updated_at DESC LIMIT ?"
        params.append(max(1, min(limit, 1000)))
        with self._connect() as conn:
            rows = conn.execute(query, params).fetchall()
        return [
            {"key": row["key"], "value": _normalize_jsonish(row["value_json"] or "{}"), "updated_at": row["updated_at"]}
            for row in rows
        ]

    # ---- procedural (autogenerated tools) ----
    def procedural_register(
        self,
        *,
        name: str,
        description: str,
        script_path: str,
        signature: dict[str, Any],
        tags: list[str],
        created_by_agent: str,
    ) -> dict[str, Any]:
        with self._connect() as conn:
            conn.execute(
                """
                INSERT INTO procedural (name, description, script_path, signature_json, tags, created_by_agent, active)
                VALUES (?, ?, ?, ?, ?, ?, 1)
                ON CONFLICT(name) DO UPDATE SET
                    description = excluded.description,
                    script_path = excluded.script_path,
                    signature_json = excluded.signature_json,
                    tags = excluded.tags,
                    active = 1
                """,
                (
                    name.strip(),
                    description.strip(),
                    str(script_path),
                    json.dumps(signature, ensure_ascii=True, default=str),
                    json.dumps(tags, ensure_ascii=True),
                    created_by_agent.strip(),
                ),
            )
        return {"name": name.strip(), "script_path": str(script_path), "active": True}

    def procedural_list(self, *, tag: str = "", include_inactive: bool = False) -> list[dict[str, Any]]:
        query = "SELECT * FROM procedural"
        conditions: list[str] = []
        params: list[Any] = []
        if not include_inactive:
            conditions.append("active = 1")
        if tag.strip():
            conditions.append("tags LIKE ?")
            params.append(f'%"{tag.strip()}"%')
        if conditions:
            query += " WHERE " + " AND ".join(conditions)
        query += " ORDER BY created_at DESC"
        with self._connect() as conn:
            rows = conn.execute(query, params).fetchall()
        return [
            {
                "name": row["name"],
                "description": row["description"],
                "script_path": row["script_path"],
                "signature": _normalize_jsonish(row["signature_json"] or "{}"),
                "tags": _normalize_jsonish(row["tags"] or "[]"),
                "created_by_agent": row["created_by_agent"],
                "created_at": row["created_at"],
                "active": bool(row["active"]),
            }
            for row in rows
        ]

    def procedural_get(self, name: str) -> dict[str, Any] | None:
        with self._connect() as conn:
            row = conn.execute("SELECT * FROM procedural WHERE name = ?", (name.strip(),)).fetchone()
        if not row:
            return None
        return {
            "name": row["name"],
            "description": row["description"],
            "script_path": row["script_path"],
            "signature": _normalize_jsonish(row["signature_json"] or "{}"),
            "tags": _normalize_jsonish(row["tags"] or "[]"),
            "created_by_agent": row["created_by_agent"],
            "created_at": row["created_at"],
            "active": bool(row["active"]),
        }

    def procedural_deactivate(self, name: str) -> bool:
        with self._connect() as conn:
            cursor = conn.execute("UPDATE procedural SET active = 0 WHERE name = ?", (name.strip(),))
            return cursor.rowcount > 0

    def procedural_purge_inactive(self) -> int:
        with self._connect() as conn:
            cursor = conn.execute("DELETE FROM procedural WHERE active = 0")
            return int(cursor.rowcount or 0)

    def procedural_purge_all(self) -> int:
        with self._connect() as conn:
            cursor = conn.execute("DELETE FROM procedural")
            return int(cursor.rowcount or 0)

    # ---- generated_graphs ----
    def graph_register(
        self,
        *,
        name: str,
        purpose: str,
        system_prompt: str,
        tool_whitelist: list[str],
        reset_policy: str,
        created_by_agent: str,
    ) -> dict[str, Any]:
        with self._connect() as conn:
            conn.execute(
                """
                INSERT INTO generated_graphs (
                    name, purpose, system_prompt, tool_whitelist_json, reset_policy, created_by_agent, active
                ) VALUES (?, ?, ?, ?, ?, ?, 1)
                ON CONFLICT(name) DO UPDATE SET
                    purpose = excluded.purpose,
                    system_prompt = excluded.system_prompt,
                    tool_whitelist_json = excluded.tool_whitelist_json,
                    reset_policy = excluded.reset_policy,
                    active = 1
                """,
                (
                    name.strip(),
                    purpose.strip(),
                    system_prompt,
                    json.dumps(tool_whitelist, ensure_ascii=True),
                    reset_policy.strip() or "on_reset",
                    created_by_agent.strip(),
                ),
            )
        return {"name": name.strip(), "active": True}

    def graph_list(self, *, include_inactive: bool = False) -> list[dict[str, Any]]:
        query = "SELECT * FROM generated_graphs"
        if not include_inactive:
            query += " WHERE active = 1"
        query += " ORDER BY created_at DESC"
        with self._connect() as conn:
            rows = conn.execute(query).fetchall()
        return [
            {
                "name": row["name"],
                "purpose": row["purpose"],
                "system_prompt": row["system_prompt"],
                "tool_whitelist": _normalize_jsonish(row["tool_whitelist_json"] or "[]"),
                "reset_policy": row["reset_policy"],
                "created_by_agent": row["created_by_agent"],
                "created_at": row["created_at"],
                "active": bool(row["active"]),
            }
            for row in rows
        ]

    def graph_get(self, name: str) -> dict[str, Any] | None:
        with self._connect() as conn:
            row = conn.execute("SELECT * FROM generated_graphs WHERE name = ?", (name.strip(),)).fetchone()
        if not row:
            return None
        return {
            "name": row["name"],
            "purpose": row["purpose"],
            "system_prompt": row["system_prompt"],
            "tool_whitelist": _normalize_jsonish(row["tool_whitelist_json"] or "[]"),
            "reset_policy": row["reset_policy"],
            "created_by_agent": row["created_by_agent"],
            "created_at": row["created_at"],
            "active": bool(row["active"]),
        }

    def graph_drop(self, name: str) -> bool:
        with self._connect() as conn:
            cursor = conn.execute("UPDATE generated_graphs SET active = 0 WHERE name = ?", (name.strip(),))
            return cursor.rowcount > 0

    def graph_purge_on_reset(self) -> int:
        with self._connect() as conn:
            cursor = conn.execute("DELETE FROM generated_graphs WHERE reset_policy = 'on_reset'")
            return int(cursor.rowcount or 0)

    # ---- agent_wake_queue ----
    def enqueue_wake(self, *, target_agent: str, task: dict[str, Any], priority: int = 0) -> int:
        with self._connect() as conn:
            cursor = conn.execute(
                "INSERT INTO agent_wake_queue (target_agent, task_json, priority) VALUES (?, ?, ?)",
                (target_agent.strip(), json.dumps(task, ensure_ascii=True, default=str), priority),
            )
            return int(cursor.lastrowid)

    def claim_wake_item(self, *, target_agent: str, claimer_pid: int) -> dict[str, Any] | None:
        """Atomically claim the highest-priority unclaimed wake item for a given agent."""
        now = _utc_now_db()
        with self._connect() as conn:
            conn.execute("BEGIN IMMEDIATE")
            row = conn.execute(
                """
                SELECT id, task_json FROM agent_wake_queue
                WHERE target_agent = ? AND claimed_at = ''
                ORDER BY priority DESC, id ASC
                LIMIT 1
                """,
                (target_agent.strip(),),
            ).fetchone()
            if not row:
                conn.rollback()
                return None
            conn.execute(
                "UPDATE agent_wake_queue SET claimed_at = ?, claimer_pid = ? WHERE id = ?",
                (now, claimer_pid, row["id"]),
            )
            conn.commit()
        return {"id": int(row["id"]), "task": _normalize_jsonish(row["task_json"] or "{}"), "claimed_at": now}

    def list_wake_queue(self, *, target_agent: str = "", include_claimed: bool = False) -> list[dict[str, Any]]:
        query = "SELECT * FROM agent_wake_queue"
        conditions: list[str] = []
        params: list[Any] = []
        if target_agent.strip():
            conditions.append("target_agent = ?")
            params.append(target_agent.strip())
        if not include_claimed:
            conditions.append("claimed_at = ''")
        if conditions:
            query += " WHERE " + " AND ".join(conditions)
        query += " ORDER BY priority DESC, id ASC"
        with self._connect() as conn:
            rows = conn.execute(query, params).fetchall()
        return [
            {
                "id": row["id"],
                "target_agent": row["target_agent"],
                "task": _normalize_jsonish(row["task_json"] or "{}"),
                "priority": row["priority"],
                "enqueued_at": row["enqueued_at"],
                "claimed_at": row["claimed_at"] or None,
                "claimer_pid": row["claimer_pid"],
            }
            for row in rows
        ]

    # ==================================================================
    # Helpers
    # ==================================================================
    def _task_key(self, target_ip: str, action: str) -> str:
        return f"{target_ip.strip()}::{action.strip()}"

    def _intel_row_to_dict(self, row: sqlite3.Row) -> dict[str, Any]:
        return {
            "id": row["id"],
            "target_ip": row["target_ip"],
            "port": row["port"],
            "service": row["service"],
            "finding_type": row["finding_type"],
            "severity": row["severity"],
            "details": _normalize_jsonish(row["details"] or "{}"),
            "source_agent": row["source_agent"],
            "status": row["status"],
            "tags": _normalize_jsonish(row["tags"] or "[]"),
            "fingerprint": row["fingerprint"],
            "timestamp": row["timestamp"],
            "updated_at": row["updated_at"],
        }

    def _task_row_to_dict(self, row: sqlite3.Row) -> dict[str, Any]:
        return {
            "id": row["id"],
            "target_ip": row["target_ip"],
            "action": row["action"],
            "task_key": row["task_key"],
            "assigned_agent": row["assigned_agent"],
            "status": row["status"],
            "lease_expires_at": row["lease_expires_at"],
            "metadata": _normalize_jsonish(row["metadata"] or "{}"),
            "result": _normalize_jsonish(row["result"] or "{}"),
            "created_at": row["created_at"],
            "updated_at": row["updated_at"],
        }

    def _message_row_to_dict(self, row: sqlite3.Row) -> dict[str, Any]:
        return {
            "id": row["id"],
            "sender_agent": row["sender_agent"],
            "recipient_agent": row["recipient_agent"],
            "subject": row["subject"],
            "message_type": row["message_type"],
            "body": row["body"],
            "related_task_id": row["related_task_id"],
            "related_target_ip": row["related_target_ip"],
            "status": row["status"],
            "created_at": row["created_at"],
            "read_at": row["read_at"],
            "metadata": _normalize_jsonish(row["metadata"] or "{}"),
        }
